galaksija2024.mem: galaxya42.rom
	./galaksija2024.py
	cp galaksija2024.mem ../../galaksija2024.mem

galaxya42.rom: eprom.zip
	unzip -o eprom.zip

clean:
	rm -f chargen4.rom galaxya42.rom galaksija2024.mem *~
